[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[theme]
primaryColor = "#0d5c6e"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#e8f4f6"
textColor = "#0d1b3e"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false

